### ISSUE TITLE
Ajout des critères "NT" dans la synthèse et passage des AAA à "NT" au lieu de "NA"

### ISSUE THREAD

**Issue by juliemoynat** [DISIC/rgaa_modeles_documents#2]
Bonjour,

Dans la grille de test, pourquoi les critères non testés "NT" ne sont-ils pas présents dans la synthèse ?
Il me semble pertinent de les y ajouter afin de pouvoir vérifier facilement à ce niveau que toutes les cases ont été saisies (et donc aussi pour vérifier que le compte est bon).

Par ailleurs, les critères AAA sont par défaut en non applicable "NA" alors que NA signifie (je cite le mode d'emploi) : "Aucun élément dans la page ne concerne le critère". Il me semble donc que les critères de niveau AAA devraient plutôt être à "NT" par défaut (ou vides).

**Comment by Etat-Plateforme** [comment]
Bonjour,

> « Dans la grille de test, pourquoi les critères non testés "NT" ne sont-ils pas présents dans la synthèse ? »

Effectivement, cette information pourrait être utile pour s'assurer d'avoir tester tous les critères. Le tableau a été modifié en conséquence.

> « Il me semble donc que les critères de niveau AAA devraient plutôt être à "NT" par défaut (ou vides) »

Ceci n'est pas systématique et dépend du niveau de conformité visé par l'audit. Il est possible de réaliser un audit pour le niveau AA, ainsi les critères A et AA sont applicables, mais les critères AAA sont non applicables puisqu'ils sortent du champ de l'audit. La grille est donc par défaut paramétrée pour un audit AA.
