### ISSUE TITLE
Base de calcul érroné

### ISSUE THREAD

**Issue by stevenMouret** [DISIC/rgaa_modeles_documents#3]
Bonjour,

Dans le document rgaa3.0.grille-de-test-full.ods la base de calcul est incorrecte.

Dans la feuille BaseDeCalcul :
En exemple prenons le critère 1.10 sur la page 02 cellule F10. La fonction, =$P02.$E12 devrait être =$P02.$E13
L'erreur va de la page 02 à la page 15. Presque toutes les lignes du document sont fausses.

Je suis en train de corriger la grille si cela vous intéresse.

Pour information j'avais déjà signalé ce problème il y a plus d'un an quand le RGAA n'était pas encore sur Github.

**Comment by Etat-Plateforme** [comment]
Bonjour,

Merci pour cette alerte et votre proposition de partager votre version corrigée de la grille.
Grâce à vous nous pourrons mettre à jour ce document.

**Comment by stevenMouret** [comment]
[rgaa3.0.grille-de-test-full.ods.zip](https://github.com/DISIC/rgaa_modeles_documents/files/348157/rgaa3.0.grille-de-test-full.ods.zip)

**Comment by Etat-Plateforme** [comment]
La version corrigée est maintenant en ligne. Encore merci pour votre vigilance et votre aide.
